#!/bin/bash
echo "============================================================"
echo "CSG Sprint Reporter - Credential Setup"
echo "============================================================"
echo ""
echo "This wizard will help you configure your credentials."
echo "You'll need:"
echo "  1. Your Jira email"
echo "  2. Jira API token (get from: id.atlassian.com)"
echo "  3. Fathom API key (get from: fathom.video/customize)"
echo ""
echo "NOTE: When asked for Claude API key, just press Enter"
echo "      (Layden has already configured a shared team key)"
echo ""
read -p "Press Enter to continue..."

cd "$(dirname "$0")"
python3 csg-sprint-reporter.py --config

echo ""
echo "============================================================"
echo "SETUP COMPLETE!"
echo "============================================================"
echo ""
echo "Next step: Run ./run_report.sh to generate your first report"
echo ""
read -p "Press Enter to continue..."
